name: "Terraform Plan"

on:
  push:

defaults:
  run:
    working-directory: terraform

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate -no-color
      - run: terraform plan -no-color
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}